name = "Dezelo: Eternal Frost"
author = "tgskoz"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "20a3464bc83504818f7d6630d744301cdb0201aeeb997c3d6facebc5dccbf9ca"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.255"

[options]
acceptable-game-versions = ["1.21"]
